-- MySQL Script generated by MySQL Workbench
-- Fri Mar 13 00:02:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mitube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mitube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mitube` DEFAULT CHARACTER SET utf8 ;
USE `mitube` ;

-- -----------------------------------------------------
-- Table `mitube`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mitube`.`users` ;

CREATE TABLE IF NOT EXISTS `mitube`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `birth_date` DATE NOT NULL,
  `sex` ENUM('male', 'female') NULL,
  `country` VARCHAR(45) NOT NULL,
  `zip_code` VARCHAR(6) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mitube`.`video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mitube`.`video` ;

CREATE TABLE IF NOT EXISTS `mitube`.`video` (
  `id_video` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  `upload_datetime` DATETIME NOT NULL,
  `size` INT NOT NULL,
  `length` INT NOT NULL,
  `file_name` VARCHAR(45) NOT NULL,
  `thumbnail` VARCHAR(225) NOT NULL,
  `views` INT NOT NULL,
  `likes` INT NOT NULL,
  `dislikes` INT NOT NULL,
  `state` ENUM('public', 'hidden', 'private') NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_video`),
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_video_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mitube`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mitube`.`channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mitube`.`channel` ;

CREATE TABLE IF NOT EXISTS `mitube`.`channel` (
  `id_channel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `desciption` VARCHAR(200) NULL,
  `creation_date` DATE NOT NULL,
  `id_user` INT NULL,
  PRIMARY KEY (`id_channel`),
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_channel_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mitube`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mitube`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mitube`.`tags` ;

CREATE TABLE IF NOT EXISTS `mitube`.`tags` (
  `id_tag` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mitube`.`playlists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mitube`.`playlists` ;

CREATE TABLE IF NOT EXISTS `mitube`.`playlists` (
  `id_playlist` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `creation_date` DATE NOT NULL,
  `state` ENUM('public', 'private') NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_playlist`),
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_playlists_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mitube`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mitube`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mitube`.`comments` ;

CREATE TABLE IF NOT EXISTS `mitube`.`comments` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(500) NOT NULL,
  `creation_datetime` DATETIME NOT NULL,
  `id_user` INT NOT NULL,
  `id_video` INT NOT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `id_video_idx` (`id_video` ASC) VISIBLE,
  CONSTRAINT `fk_comments_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mitube`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_video`
    FOREIGN KEY (`id_video`)
    REFERENCES `mitube`.`video` (`id_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mitube`.`user_channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mitube`.`user_channel` ;

CREATE TABLE IF NOT EXISTS `mitube`.`user_channel` (
  `id_user` INT NOT NULL,
  `id_channel` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_channel`),
  INDEX `id_channel_idx` (`id_channel` ASC) VISIBLE,
  CONSTRAINT `fk_user_channel_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mitube`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_channel`
    FOREIGN KEY (`id_channel`)
    REFERENCES `mitube`.`channel` (`id_channel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mitube`.`video_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mitube`.`video_tags` ;

CREATE TABLE IF NOT EXISTS `mitube`.`video_tags` (
  `id_video` INT NOT NULL,
  `id_tag` INT NOT NULL,
  PRIMARY KEY (`id_video`, `id_tag`),
  INDEX `id_tag_idx` (`id_tag` ASC) VISIBLE,
  CONSTRAINT `fk_vtags_video`
    FOREIGN KEY (`id_video`)
    REFERENCES `mitube`.`video` (`id_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_tag`
    FOREIGN KEY (`id_tag`)
    REFERENCES `mitube`.`tags` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mitube`.`user_comment_vote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mitube`.`user_comment_vote` ;

CREATE TABLE IF NOT EXISTS `mitube`.`user_comment_vote` (
  `id_user` INT NOT NULL,
  `id_comment` INT NOT NULL,
  `comment_vote` ENUM('like', 'dislike') NOT NULL,
  `comment_vote_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `id_comment_idx` (`id_comment` ASC) VISIBLE,
  CONSTRAINT `fk_ucv_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mitube`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ucv_comment`
    FOREIGN KEY (`id_comment`)
    REFERENCES `mitube`.`comments` (`id_comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mitube`.`user_video_vote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mitube`.`user_video_vote` ;

CREATE TABLE IF NOT EXISTS `mitube`.`user_video_vote` (
  `id_user` INT NOT NULL,
  `id_video` INT NOT NULL,
  `video_vote` ENUM('like', 'dislike') NOT NULL,
  `video_vote_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`id_user`, `id_video`),
  INDEX `id_video_idx` (`id_video` ASC) VISIBLE,
  CONSTRAINT `fk_uvv_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `mitube`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uvv_video`
    FOREIGN KEY (`id_video`)
    REFERENCES `mitube`.`video` (`id_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mitube`.`video_playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mitube`.`video_playlist` ;

CREATE TABLE IF NOT EXISTS `mitube`.`video_playlist` (
  `id_video` INT NOT NULL,
  `id_playlist` INT NOT NULL,
  PRIMARY KEY (`id_video`, `id_playlist`),
  INDEX `id_playlist_idx` (`id_playlist` ASC) VISIBLE,
  CONSTRAINT `fk_vplaylist_video`
    FOREIGN KEY (`id_video`)
    REFERENCES `mitube`.`video` (`id_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_playlist`
    FOREIGN KEY (`id_playlist`)
    REFERENCES `mitube`.`playlists` (`id_playlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
