-- MySQL Script generated by MySQL Workbench
-- Wed Mar 11 11:19:03 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Optica_culo_botella
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Optica_culo_botella
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optica_culo_botella` DEFAULT CHARACTER SET utf8 ;
USE `Optica_culo_botella` ;

-- -----------------------------------------------------
-- Table `Optica_culo_botella`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica_culo_botella`.`clientes` ;

CREATE TABLE IF NOT EXISTS `Optica_culo_botella`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `piso` VARCHAR(10) NULL,
  `puerta` VARCHAR(4) NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `cp` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `correo_electronioc` VARCHAR(45) NOT NULL,
  `fecha_registro` DATE NOT NULL,
  `recomendador` INT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `idClientes_idx` (`recomendador` ASC) VISIBLE,
  CONSTRAINT `idClientes`
    FOREIGN KEY (`recomendador`)
    REFERENCES `Optica_culo_botella`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_culo_botella`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica_culo_botella`.`ventas` ;

CREATE TABLE IF NOT EXISTS `Optica_culo_botella`.`ventas` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `vendedor` VARCHAR(45) NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_venta`),
  INDEX `idClientes_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `Optica_culo_botella`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_culo_botella`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica_culo_botella`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `Optica_culo_botella`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `piso` VARCHAR(10) NULL,
  `puerta` VARCHAR(4) NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `cp` INT NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `fax` INT NULL,
  `nif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_proveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_culo_botella`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica_culo_botella`.`marca` ;

CREATE TABLE IF NOT EXISTS `Optica_culo_botella`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT NOT NULL,
  PRIMARY KEY (`id_marca`),
  INDEX `idProveedor_idx` (`id_proveedor` ASC) VISIBLE,
  CONSTRAINT `idProveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `Optica_culo_botella`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_culo_botella`.`gafas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica_culo_botella`.`gafas` ;

CREATE TABLE IF NOT EXISTS `Optica_culo_botella`.`gafas` (
  `id_gafas` INT NOT NULL AUTO_INCREMENT,
  `id_marca` INT NOT NULL,
  `graduacion_derecha` INT NOT NULL,
  `graduacion_izquierda` INT NOT NULL,
  `tipo_montura` ENUM('flotante', 'pasta', 'metalica') NOT NULL,
  `color_montura` VARCHAR(45) NOT NULL,
  `color_derecho` VARCHAR(45) NOT NULL,
  `color_izquiedo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_gafas`),
  INDEX `idMarca_idx` (`id_marca` ASC) VISIBLE,
  CONSTRAINT `idMarca`
    FOREIGN KEY (`id_marca`)
    REFERENCES `Optica_culo_botella`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica_culo_botella`.`detalle_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Optica_culo_botella`.`detalle_venta` ;

CREATE TABLE IF NOT EXISTS `Optica_culo_botella`.`detalle_venta` (
  `id_detalle` INT NOT NULL AUTO_INCREMENT,
  `id_venta` INT NOT NULL,
  `id_gafa` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` FLOAT NOT NULL,
  INDEX `idGafas_idx` (`id_gafa` ASC) VISIBLE,
  PRIMARY KEY (`id_detalle`),
  CONSTRAINT `idVentas`
    FOREIGN KEY (`id_venta`)
    REFERENCES `Optica_culo_botella`.`ventas` (`id_venta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idGafas`
    FOREIGN KEY (`id_gafa`)
    REFERENCES `Optica_culo_botella`.`gafas` (`id_gafas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
