-- MySQL Script generated by MySQL Workbench
-- Thu Mar 12 12:27:49 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria_mario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria_mario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria_mario` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria_mario` ;


-- -----------------------------------------------------
-- Table `pizzeria_mario`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria_mario`.`cliente` ;

CREATE TABLE IF NOT EXISTS `pizzeria_mario`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_1` VARCHAR(45) NOT NULL,
  `apellido_2` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(5) NOT NULL,
  `piso` VARCHAR(10) NOT NULL,
  `puerta` VARCHAR(4) NULL,
  `cp` INT NOT NULL,
  `ciudad` VARCHAR(20) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria_mario`.`tienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria_mario`.`tienda` ;

CREATE TABLE IF NOT EXISTS `pizzeria_mario`.`tienda` (
  `id_tienda` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `cp` VARCHAR(5) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria_mario`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria_mario`.`empleado` ;

CREATE TABLE IF NOT EXISTS `pizzeria_mario`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `id_tienda` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_1` VARCHAR(45) NOT NULL,
  `apellido_2` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(9) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `papel` ENUM('repartidor', 'cocinero') NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `id_tienda_idx` (`id_tienda` ASC) VISIBLE,
  CONSTRAINT `id_tienda`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `pizzeria_mario`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria_mario`.`categoria_pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria_mario`.`categoria_pizza` ;

CREATE TABLE IF NOT EXISTS `pizzeria_mario`.`categoria_pizza` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria_mario`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria_mario`.`producto` ;

CREATE TABLE IF NOT EXISTS `pizzeria_mario`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `imagen` VARCHAR(100) NOT NULL,
  `precio` DECIMAL NOT NULL,
  `tipo` ENUM('pizza', 'hamburguesa', 'bebida') NOT NULL,
  `id_categoria` INT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `id_categoria_idx` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `id_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `pizzeria_mario`.`categoria_pizza` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria_mario`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria_mario`.`pedido` ;

CREATE TABLE IF NOT EXISTS `pizzeria_mario`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_tienda` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `tipo_entrega` ENUM('domicilio', 'tienda') NOT NULL,
  `precio_total` DECIMAL NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `id_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `id_tienda_idx` (`id_tienda` ASC) VISIBLE,
  CONSTRAINT `id_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `pizzeria_mario`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_tienda`
    FOREIGN KEY (`id_tienda`)
    REFERENCES `pizzeria_mario`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria_mario`.`detalle_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria_mario`.`detalle_pedido` ;

CREATE TABLE IF NOT EXISTS `pizzeria_mario`.`detalle_pedido` (
  `id_detalle_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NOT NULL,
  `id_pedido` INT NOT NULL,
  `precio_unitario` DECIMAL NOT NULL,
  `cantidad_producto` INT NOT NULL,
  PRIMARY KEY (`id_detalle_pedido`),
  INDEX `id_producto_idx` (`id_producto` ASC) VISIBLE,
  INDEX `id_pedido_idx` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `id_producto`
    FOREIGN KEY (`id_producto`)
    REFERENCES `pizzeria_mario`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `pizzeria_mario`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria_mario`.`entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pizzeria_mario`.`entrega` ;

CREATE TABLE IF NOT EXISTS `pizzeria_mario`.`entrega` (
  `id_entrega` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora_entrega` DATETIME NOT NULL,
  `id_empleado` INT NOT NULL,
  `id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_entrega`),
  INDEX `id_empleado_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `id_pedido_idx` (`id_pedido` ASC) VISIBLE,
  UNIQUE INDEX `id_pedido_UNIQUE` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `id_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `pizzeria_mario`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `pizzeria_mario`.`pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
